"""Static, hashed n-gram embeddings for `search_categories`' long-tail extension.

Backs the embeddings step of intent-based place search (#356, sub-issue 2/2
of #307). #355 shipped a curated lexical fallback (categories.py's
token-coverage matching against data/category_synonyms.csv) that handles
common phrase intents ("fix my cracked phone screen"). It cannot handle a
phrase whose words never appear in the lexicon at all ("somewhere calm to
read for an hour" shares no token with any slug, path segment, or synonym
row) — that is the long tail this module extends into.

Deliberately NOT a neural sentence embedding: no model, no API key, no
network, no torch/onnx runtime. A "sentence" here is just the bag of
tokenized words behind a taxonomy row (see categories._row_word_set) or a
query. Each word contributes itself plus its padded character n-grams
(n=3,4) as features; every feature hashes (via zlib.crc32, NOT Python's
randomized `hash()`, so the artifact is reproducible across regenerations
and processes) into one of EMBED_DIM buckets with a deterministic +/-1
sign — the standard "feature hashing" trick (scikit-learn's
HashingVectorizer uses the same idea). Character n-grams give a query a
fighting chance against a taxonomy row even with zero shared whole words
("cracked" and "crack" share most of their trigrams), which is the entire
value a static bag-of-words model adds over plain token overlap.

Pure stdlib: `array`, `struct`, `zlib`, `math`. No numpy, no third-party
dependency at all — the package-size increase from this feature is just
the bundled artifact (see data/README.md for its measured size).

The bundled artifact (src/placeroot/data/category_embeddings.bin) is
regenerated by scripts/build_category_embeddings.py, which imports this
module for the encoding and categories.py for row text — same feature
extraction on both sides of the build/runtime seam, or query and row
vectors would live in different spaces.
"""

from __future__ import annotations

import array
import importlib.resources
import math
import struct
import zlib

# Dimensionality of the hashed embedding space. 128 keeps the per-query
# dot-product cost trivial in pure Python (~2,100 rows * 128 dims = ~270k
# multiply-adds, well under a millisecond budget — see the cold-start
# measurement in the PR) while giving the hash buckets enough room that
# collisions between unrelated features stay rare across ~15k distinct
# n-gram/word features drawn from the taxonomy.
EMBED_DIM = 128

_NGRAM_SIZES = (3, 4)

_ARTIFACT_MAGIC = b"PRCE1"
_QUANT_SCALE = 127

_ARTIFACT: tuple[list[str], int, array.array] | None = None
_ARTIFACT_LOAD_ATTEMPTED = False


def _char_ngrams(word: str) -> list[str]:
    """Padded character n-grams ("cat" -> "^cat$" -> "^ca","cat","at$" for
    n=3) so a word's edges count as features too, not just its middle."""
    padded = f"^{word}$"
    grams = []
    for n in _NGRAM_SIZES:
        if len(padded) <= n:
            grams.append(padded)
            continue
        grams.extend(padded[i : i + n] for i in range(len(padded) - n + 1))
    return grams


def _features(words: list[str]) -> list[tuple[str, float]]:
    """(feature, weight) pairs for a bag of words: the whole word (weight
    2.0, so an exact shared word counts for more than a shared fragment)
    plus its character n-grams (weight 1.0 each)."""
    feats = []
    for w in words:
        feats.append((f"W:{w}", 2.0))
        feats.extend((f"G:{g}", 1.0) for g in _char_ngrams(w))
    return feats


def _hash_bucket_sign(feature: str, dim: int) -> tuple[int, int]:
    """Deterministic bucket + sign for one feature string.

    zlib.crc32, not Python's built-in hash() — hash() is salted per
    process (PYTHONHASHSEED) by default, which would make the artifact
    built in one process score differently against a query embedded in
    another. crc32 is stable across processes, machines, and Python
    versions, which is what lets the bundled artifact and every future
    runtime query agree on the same feature space.
    """
    h = zlib.crc32(feature.encode("utf-8")) & 0xFFFFFFFF
    bucket = h % dim
    sign = 1 if (h >> 31) & 1 == 0 else -1
    return bucket, sign


def embed_words(words: list[str], dim: int = EMBED_DIM) -> list[float]:
    """Bag-of-words -> unit-normalized dense vector of length `dim`.

    Empty input (e.g. a stopword-only query) returns an all-zero vector;
    callers should treat that as "no signal" rather than compute cosine
    against it (cosine against a zero vector is 0 anyway, which sorts
    last, so callers don't need a special case).
    """
    vec = [0.0] * dim
    for feature, weight in _features(words):
        bucket, sign = _hash_bucket_sign(feature, dim)
        vec[bucket] += sign * weight
    norm = math.sqrt(sum(x * x for x in vec))
    if norm > 0:
        vec = [x / norm for x in vec]
    return vec


def save_artifact(path, slugs: list[str], vectors: list[list[float]], dim: int = EMBED_DIM) -> None:
    """Write the compact binary artifact scripts/build_category_embeddings.py
    produces. Format (all integers little-endian):

        b"PRCE1"            5 bytes, magic + version
        dim: uint16, n: uint32
        n * (slug_len: uint8, slug: utf-8 bytes)   -- slug table, row order
        n * dim int8 values                        -- quantized vectors, row-major

    Vectors are expected unit-normalized (embed_words does this); each
    component is quantized to int8 by scaling by 127 and rounding, which
    caps quantization error per component at <1/127 (~0.008) — the tail
    extension this backs is a coarse rank, not exact cosine, so this is
    plenty of precision for a fraction of float32/float16's size.
    """
    if len(slugs) != len(vectors):
        raise ValueError("slugs and vectors must be the same length")
    with open(path, "wb") as f:
        f.write(_ARTIFACT_MAGIC)
        f.write(struct.pack("<HI", dim, len(slugs)))
        for slug in slugs:
            b = slug.encode("utf-8")
            if len(b) > 255:
                raise ValueError(f"slug too long to encode: {slug!r}")
            f.write(struct.pack("<B", len(b)))
            f.write(b)
        flat = array.array("b")
        for vec in vectors:
            if len(vec) != dim:
                raise ValueError("vector dimension mismatch")
            flat.extend(max(-_QUANT_SCALE, min(_QUANT_SCALE, round(x * _QUANT_SCALE))) for x in vec)
        f.write(flat.tobytes())


def _artifact_path():
    return importlib.resources.files("placeroot") / "data" / "category_embeddings.bin"


def _load_artifact() -> tuple[list[str], int, array.array] | None:
    """Parse and cache the bundled artifact. Returns None (cached) if the
    file is missing, truncated, or not this format — the whole point of
    #356's fallback contract: a missing/corrupt artifact silently
    degrades `search_categories` to lexical-only, never an error."""
    global _ARTIFACT, _ARTIFACT_LOAD_ATTEMPTED
    if _ARTIFACT_LOAD_ATTEMPTED:
        return _ARTIFACT
    _ARTIFACT_LOAD_ATTEMPTED = True

    try:
        data = _artifact_path().read_bytes()
    except OSError:
        return None

    try:
        if data[:5] != _ARTIFACT_MAGIC:
            return None
        dim, n = struct.unpack_from("<HI", data, 5)
        offset = 11
        slugs = []
        for _ in range(n):
            (slen,) = struct.unpack_from("<B", data, offset)
            offset += 1
            slugs.append(data[offset : offset + slen].decode("utf-8"))
            offset += slen
        flat = array.array("b")
        flat.frombytes(data[offset : offset + n * dim])
    except (struct.error, ValueError, UnicodeDecodeError, IndexError):
        return None

    _ARTIFACT = (slugs, dim, flat)
    return _ARTIFACT


def reset_cache() -> None:
    """Test hook: drop the memoized artifact so the next call re-reads
    from disk (or re-discovers it is missing)."""
    global _ARTIFACT, _ARTIFACT_LOAD_ATTEMPTED
    _ARTIFACT = None
    _ARTIFACT_LOAD_ATTEMPTED = False


def embedding_similarities(query_words: list[str]) -> list[tuple[str, float]]:
    """(slug, cosine) for every row in the bundled artifact, unsorted.

    [] if the artifact is missing/unreadable (see _load_artifact) or the
    query has no usable words — never raises, per #356's fallback
    contract. Cosine is computed against the dequantized (/127) stored
    vectors; both sides are close to unit norm so the dot product is
    already the cosine similarity.
    """
    if not query_words:
        return []
    artifact = _load_artifact()
    if artifact is None:
        return []
    slugs, dim, flat = artifact
    qv = embed_words(query_words, dim)
    if all(x == 0.0 for x in qv):
        return []

    out = []
    for i, slug in enumerate(slugs):
        base = i * dim
        dot = sum(qv[j] * flat[base + j] for j in range(dim)) / _QUANT_SCALE
        out.append((slug, dot))
    return out
